title: SY-λ Code Lab
author: sylambdacode
url: https://sylambdacode.github.io/
description: 一个纯粹的计算机理论与技术博客（本站中所有内容遵循CC BY-NC 4.0协议）
show_excerpts: true

moving:
  about_you: 探索λ世界
  date_format: "%m %d"
  back_to: "首页"
  social_links:
    github: sylambdacode
timezone: Asia/Shanghai
remote_theme: huangyz0918/moving
plugins:
- jekyll-remote-theme